const icaoCodeOptions = [
  { name: "Aachen-Merzbrück Airport", iso: "DE", code: "EDKA" },
  { name: "Aalborg Airport", iso: "DK", code: "EKYT" },
  { name: "Aamby Valley Airport", iso: "IN", code: "VAAV" },
  { name: "Aandster Airstrip", iso: "NA", code: "FYAD" },
  { name: "Aarhus Airport", iso: "DK", code: "EKAH" },
  { name: "Aarhus University Hospital Helipad", iso: "DK", code: "EKAS" },
  { name: "Aasiaat Airport", iso: "GL", code: "BGAA" },
  { name: "Aba Airport", iso: "CD", code: "FZJF" },
  { name: "Aba Tenna Dejazmach Yilma International Airport", iso: "ET", code: "HADR" },
  { name: "Abadan Airport", iso: "IR", code: "OIAA" },
  { name: "Abaiang Airport", iso: "KI", code: "NGAB" },
  { name: "Abakan International Airport", iso: "RU", code: "UNAA" },
  { name: "Abbaye Airport", iso: "MR", code: "GQNE" },
  { name: "Abbeville-Buigny Baie de Somme Airfield", iso: "FR", code: "LFOI" },
  { name: "Abbeyshrule Aerodrome", iso: "IE", code: "EIAB" },
  { name: "Abbotsford International Airport", iso: "CA", code: "CYXX" },
  { name: "Abdelhafid Boussouf Bou Chekif Airport", iso: "DZ", code: "DAOB" },
  { name: "Abdul Rachman Saleh Airport", iso: "ID", code: "WARA" },
  { name: "Abeche Airport", iso: "TD", code: "FTTC" },
  { name: "Abeid Amani Karume International Airport", iso: "TZ", code: "HTZA" },
  { name: "Abel Santamaria International Airport", iso: "CU", code: "MUSC" },
  { name: "Abemama Airport", iso: "KI", code: "NGTB" },
  { name: "Abengourou Airport", iso: "CI", code: "DIAU" },
  { name: "Aberdeen Airport", iso: "ZA", code: "FAAE" },
  { name: "Aberdeen International Airport", iso: "GB", code: "EGPD" },
  { name: "Aberdeen Regional Airport", iso: "US", code: "KABR" },
  { name: "Abha International Airport", iso: "SA", code: "OEAB" },
  { name: "Abilene Regional Airport", iso: "US", code: "KABI" },
  { name: "Abingdon Downs Airport", iso: "AU", code: "YABI" },
  { name: "Aboisso Airport", iso: "CI", code: "DIAO" },
  { name: "Abqaiq Airport", iso: "SA", code: "OEBQ" },
  { name: "Abraham González International Airport", iso: "MX", code: "MMCS" },
  { name: "Abraham Lincoln Capital Airport", iso: "US", code: "KSPI" },
  { name: "Abresso Airport", iso: "ID", code: "WASC" },
  { name: "Abruzzo Airport", iso: "IT", code: "LIBP" },
  { name: "Abu Ali Airport", iso: "SA", code: "OEAA" },
  { name: "Abu Dhabi Northeast Airport - Suweihan Air Base", iso: "AE", code: "OMAW" },
  { name: "Abu Musa Island Airport", iso: "IR", code: "OIBA" },
  { name: "Abu Simbel Airport", iso: "EG", code: "HEBL" },
  { name: "Abumumbazi Airport", iso: "CD", code: "FZFE" },
  { name: "Acadiana Regional Airport", iso: "US", code: "KARA" },
  { name: "Acado Airport", iso: "EC", code: "SEAC" },
  { name: "Accomack County Airport", iso: "US", code: "KMFV" },
  { name: "Achinsk Airport", iso: "RU", code: "UNKS" },
  { name: "ACHS Worker's Hospital Helipad", iso: "CL", code: "SHAC" },
  { name: "Achuar Airstrip", iso: "EC", code: "SEAT" },
  { name: "Achuentza Airport", iso: "EC", code: "SEAH" },
  { name: "Ad Dakhla Airport", iso: "EG", code: "HEDK" },
  { name: "Ada Regional Airport", iso: "US", code: "KADH" },
  { name: "Adaba Airport", iso: "ET", code: "HAAD" },
  { name: "Adado Airport", iso: "SO", code: "HCAD" },
  { name: "Adak Airport", iso: "US", code: "PADK" },
  { name: "Adampur Airport", iso: "IN", code: "VIAX" },
  { name: "Adana Şakirpaşa Airport", iso: "TR", code: "LTAF" },
  { name: "Ādaži Airfield", iso: "LV", code: "EVAD" },
  { name: "Addington Field / Elizabethtown Regional Airport", iso: "US", code: "KEKX" },
  { name: "Addis Ababa Bole International Airport", iso: "ET", code: "HAAB" },
  { name: "Addison Airport", iso: "US", code: "KADS" },
  { name: "Adelaide International Airport", iso: "AU", code: "YPAD" },
  { name: "Adels Grove Airport", iso: "AU", code: "YALG" },
  { name: "Aden Adde International Airport", iso: "SO", code: "HCMM" },
  { name: "Aden International Airport", iso: "YE", code: "OYAA" },
  { name: "Adícora Airport", iso: "VE", code: "SVAD" },
  { name: "Adirondack Regional Airport", iso: "US", code: "KSLK" },
  { name: "Adisumarmo Airport", iso: "ID", code: "WAHQ" },
  { name: "Adisutjipto International Airport", iso: "ID", code: "WAHH" },
  { name: "Adıyaman Airport", iso: "TR", code: "LTCP" },
  { name: "Adjumani Airport", iso: "UG", code: "HUAJ" },
  { name: "Adnan Menderes International Airport", iso: "TR", code: "LTBJ" },
  { name: "Adolfo López Mateos International Airport", iso: "MX", code: "MMTO" },
  { name: "Adolfo Suárez Madrid–Barajas Airport", iso: "ES", code: "LEMD" },
  { name: "Adona Heliport", iso: "IE", code: "EIAH" },
]

export default icaoCodeOptions
